services:
  frontend:
    build: .
    container_name: fernangus-mantenimiento
    volumes:
      - ./app:/var/www/html/app
      - ./config/prod/virtualhost/fernangus-mantenimiento.chickenkiller.com.conf:/etc/apache2/sites-enabled/fernangus-films.mantenimiento.com.conf
    ports:
      - "8082:80"
    restart: always  # Se inicia automáticamente en producción
