services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fernangus-mantenimiento
    volumes:
      - ./app:/var/www/html/app
      - ./config/dev/virtualhost/fernangus-mantenimiento.dev.com.conf:/etc/apache2/sites-enabled/fernangus-mantenimiento.dev.com.conf
    ports:
      - "8080:80"
